const ACTIONS = {
  LOGIN: 'LOGIN',
  GET_TOKEN: 'GET_TOKEN',
  GET_USER: 'GET_USER',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_ALL_DOCUMENTS: 'GET_ALL_DOCUMENTS',
  FIND_DOCUMENT: 'FIND_DOCUMENT',
};

export default ACTIONS;
